"""initial schema

Revision ID: e3f6c2cc64ff
Revises: 
Create Date: 2026-06-01 14:07:08.818439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f6c2cc64ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('equipment', 'status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'WAITING_PARTS', 'COMPLETED', 'DELIVERED', name='equipmentstatus'),
               existing_nullable=True)
    op.alter_column('maintenance', 'status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'WAITING_PARTS', 'COMPLETED', 'DELIVERED', name='equipmentstatus'),
               existing_nullable=True)
    op.alter_column('repairs', 'status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'WAITING_PARTS', 'COMPLETED', 'DELIVERED', name='equipmentstatus'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repairs', 'status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'WAITING_PARTS', 'COMPLETED', 'DELIVERED', name='equipmentstatus'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
    op.alter_column('maintenance', 'status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'WAITING_PARTS', 'COMPLETED', 'DELIVERED', name='equipmentstatus'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
    op.alter_column('equipment', 'status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'WAITING_PARTS', 'COMPLETED', 'DELIVERED', name='equipmentstatus'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
    # ### end Alembic commands ###
